version: '3'
services:
  redis:
    image: redis:5
    restart: always
    networks:
      - pek_network
  postgres:
    image: postgres:9.6
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - database_folder:/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - pek_network
  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      - REDIS_URL=redis://redis:6379
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - pek_network
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_ENV=production
      - DATABASE_PASSWORD=
      - DATABASE_USER=postgres
      - DATABASE_NAME=pek-next
      - DATABASE_HOST=postgres
    restart: always
    env_file:
      - .env
    volumes:
      - public_folder:/pek-next/public
    ports:
      - "3443:3000"
    networks:
      - pek_network
    depends_on:
      - postgres
      - redis
networks:
  pek_network:

# Add your volumes
volumes:
  public_folder:
    external:
      name: pek_public
  database_folder:
    external:
      name: pek_database
